spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_service?serverTimezone=Asia/Shanghai
    username: radon
    password: radon

mybatis:
  mapper-locations: classpath:mapper/*
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    jdbc-type-for-null: NULL

server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://47.107.38.165:8762/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 47.107.38.165

#  cloud:
#    config:
#      fail-fast: true
#      uri: http://localhost:8888


logging:
  level:
#    com.netflix.discovery: DEBUG
    org.springframework.security: DEBUG

security:
  oauth2:
    server:
      clients:
        ui:
          client-id: ui
          secret: radon
          authorized-grant-types:
            - password
            - refresh_token
          scopes: ui

        good-service:
          client-id: good-service
          secret: radon
          authorized-grant-types:
            - client_credentials
            - refresh_token
          scopes: server

        member-service:
          client-id: member-service
          secret: radon
          authorized-grant-types:
            - client_credentials
            - refresh_token
          scopes: server
