spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service/
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

server:
  port: 4000
#  cloud:
#    config:
#      fail-fast: true
#      uri: http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.38.165:8763/eureka/

logging:
  level:
    #    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: DEBUG
