spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1    #去掉路径前缀

        - id: good-service
          uri: lb://good-service/
          predicates:
            - Path=/good/**, /seckill/**, /order/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 3

server:
  port: 4000

#  cloud:
#    config:
#      fail-fast: true
#      uri: http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.38.165:8763/eureka/, http://47.107.38.165:8762/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
