spring:
  application:
    name: registry

  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888

eureka:
#  instance:
#    prefer-ip-address: true

  client:
    registerWithEureka: false
    fetchRegistry: false
