spring:
  application:
    name: registry

server:
  port:
    8762

eureka:
  instance:
    prefer-ip-address: true
    hostname: registry2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/