spring:
  application:
    name: registry

server:
  port:
    8763

eureka:
  instance:
    prefer-ip-address: true
    hostname: registry1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/