#  cloud:
#    config:
#      fail-fast: true
#      uri: http://localhost:8888

spring:
  application:
    name: account-service

server:
  port: 8600

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.38.165:8763/eureka/,http://47.107.38.165:8762/eureka/

logging:
  level:
    org.springframework.security: DEBUG
#    com.netflix: DEBUG


security:
  oauth2:
    client:
      client-id: account-service
      authorized-grant-types:
        - client_credentials
        - refresh_token
      client-secret: radon
      scope: server
      access-token-uri: http://47.107.38.165:5000/oauth/token

    resource:
      token-info-uri: http://47.107.38.165:5000/oauth/check_token