spring:
  application:
    name: registry

server:
  port:
    8762

logging:
  level:
    com.netflix.eureka: DEBUG


eureka:
  instance:
    prefer-ip-address: true
    hostname: registry2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/




# 调试下不整合config
#  cloud:
#    config:
#      fail-fast: true
#      uri: http://localhost:8888
